name: Greeter Api Generate Api Definition
on:
  push:
    branches:
      - main

jobs:
  Generate-Resources:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Generate Docs
        run: yarn build:docs
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}